siteTitle = "Jona und die Tiefseemonster"
linkPrefix = ""
description = "Theaterstück für Menschen ab sieben Jahren"
twitter = "https://twitter.com/wissimdialog"
facebook = "https://de-de.facebook.com/wissenschaftimdialog"
instagram = "https://www.instagram.com/wissenschaftimdialog/"