siteTitle = "Jona und die Tiefseemonster"
linkPrefix = ""
description = "Theaterstück für Menschen ab sieben Jahren"
twitter = "https://twitter.com/w_jahr"
facebook = "https://www.facebook.com/wissenschaftsjahr"